version: "3.6"

services:
  # Nginx Web Application
  webserver:
    container_name: traumtor-webserver
    image: nginx:alpine
    working_dir: /var/www/traumtor
    volumes:
      - .:/var/www/traumtor
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost

  # PHP-FPM
  php-fpm:
    container_name: traumtor-php-fpm
    build: docker/php-fpm
    working_dir: /var/www/traumtor
    volumes:
      - .:/var/www/traumtor
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini

  # MySQL
  mysql:
    container_name: traumtor-mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=caching_sha2_password --character-set-server=latin1 --collation-server=latin1_swedish_ci
    environment:
      - MYSQL_ROOT_PASSWORD=traumtor
      - MYSQL_DATABASE=traumtor
      - MYSQL_USER=traumtor
      - MYSQL_PASSWORD=traumtor
    ports:
      - "3306:3306"
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'

  # Redis
  redis:
    container_name: traumtor-redis
    image: redis:alpine
    volumes:
      - traumtor-redis-data:/data
    ports:
      - "6379:6379"

  # MinIO
  minio:
    container_name: traumtor-minio
    image: minio/minio:latest
    hostname: minio
    volumes:
      - traumtor-minio-data:/export
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ACCESS_KEY: E5ACE7CFB4E45EXAMPLE
      MINIO_SECRET_KEY: sk2CjuApNPfdSEE0cLlLPw2OvEXAMPLE
    command: server --console-address ":9090" /data/export

  # MailHog
  mailhog:
    container_name: traumtor-mailhog
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

  # PHPMyAdmin
  phpmyadmin:
    container_name: k2-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    volumes:
      - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - k2-phpmyadmin-data:/var/lib/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"

volumes:
  # redis-data
  traumtor-redis-data:
    driver: local
  # minio-data
  traumtor-minio-data:
    driver: local
  # phpmyadmin-data
  k2-phpmyadmin-data:
    driver: local
